### ISSUE TITLE
can't pickle a lambda

### ISSUE THREAD

**Issue by ekg** [TariqAHassan/S4Torch#14]
I'm just getting started with S4Torch, and have run into problems with the first example.

```
(s4torch39) erikg@tux03 [05:01:04 PM] [~/S4Torch] [master *]
-> % python train.py \
  --dataset=smnist \
  --batch_size=16 \
  --max_epochs=100 \
  --lr=1e-2 \
  --n_blocks=6 \
  --d_model=128 \
  --norm_type=layer
```
This yields an error:

```
Global seed set to 1234
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..                                                                                 
Traceback (most recent call last):
  File "/home/erikg/S4Torch/train.py", line 288, in <module>
    fire.Fire(main)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/fire/core.py", line 141, in Fire                                                                         
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire                                                                        
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace                                                          
    component = fn(*varargs, **kwargs)
  File "/home/erikg/S4Torch/train.py", line 284, in main
    trainer.fit(pl_model)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit                                                  
    self._call_and_handle_interrupt(
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt                           
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 78, in launch                                     
    mp.spawn(
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn                                                      
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes                                            
    process.start()
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/multiprocessing/process.py", line 121, in start                                                                        
    self._popen = self._Popen(self)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/multiprocessing/context.py", line 284, in _Popen                                                                       
    return Popen(process_obj)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__                                                            
    super().__init__(process_obj)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__                                                                   
    self._launch(process_obj)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch                                                             
    reduction.dump(process_obj, fp)
  File "/home/erikg/anaconda3/envs/s4torch39/lib/python3.9/multiprocessing/reduction.py", line 60, in dump                                                                        
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'SMnistDataset.__init__.<locals>.<lambda>'
```

It looks like a common problem with the multiprocessing library. I wonder if you have any suggestions, or if there are ways I can help you get more information about my environment. I built it up from python3.9 conda `conda create -n s4torch39 python=3.9`, to install python and pip, and then used your `pip install -r dev_requirements.txt` install guide, then `pip install git+https://github.com/TariqAHassan/S4Torch.git` and `pip install setuptools==59.5.0`.

**Comment by TariqAHassan** [comment]
Hey @ekg 👋 

I've merged some changes that _should_ resolve these pickling problems.

Also note that while my implementation of S4 performs fairly well as you can see in the README, it doesn't perform _as well_ as the one from the original authors. Albert Gu has prepared a simple implementation you may find helpful, see [here](https://github.com/HazyResearch/state-spaces/blob/4bc304d756e8cc031f4cf98ed4dbe8170f88c2e0/src/models/sequence/ss/standalone/s4d_minimal.py)).

**Comment by TariqAHassan** [comment]
Hi @ekg 

I'm going to close this issue, but please feel free to open it again if you see fit! 😃
